SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION PRODUCT_TRAN

BEGIN TRY
    SELECT * FROM Products

    COMMIT TRANSACTION PRODUCT_TRAN
    PRINT 'Transaction Succeed.'
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION PRODUCT_TRAN
    PRINT 'Transaction Failed.'
END CATCH